name: dorth
description: Dorth programming language.
version: 1.0.0
repository: https://github.com/hasanpasha/dorth

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  # quiver: ^3.2.2
  string_unescape: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
