name: dorth
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0-100.2.beta

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  quiver: ^3.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
